"""Add username in Comments

Revision ID: 606781f1f170
Revises: 262af9a5d89d
Create Date: 2024-08-13 09:25:14.484878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606781f1f170'
down_revision = '262af9a5d89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
