"""Updated Models

Revision ID: ef4b3bec6dcb
Revises: 4e39ca816358
Create Date: 2024-08-05 12:37:30.977478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4b3bec6dcb'
down_revision = '4e39ca816358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_user_uid_fkey', type_='foreignkey')
        batch_op.drop_column('user_uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_uid', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('comment_user_uid_fkey', 'user', ['user_uid'], ['uid'], ondelete='CASCADE')

    # ### end Alembic commands ###
